### ISSUE TITLE
Freddy's Tribute corruption

### ISSUE THREAD

**Issue by Heisenbergoy** [AITYunivers/NebulaFD#13]
When I try to decompile the game here: https://gamejolt.com/games/freddy-s-tribute/61948, Nebula doesn't give me errors but when I open the MFA, trying to go to any frames, viewing actives or building the app crash it. Many active icons also have the default symbol instead of what they look like in-game. These problems most likely come from how ancient the game is but hopefully a fix is possible.

**Comment by AITYunivers** [comment]
MMF2 isn't officially supported and this issue isn't in the scope of the project and will most likely never be fixed. If MMF2 ever realigns with the scope I'll reopen this issue.
