### ISSUE TITLE
this error while dumping a game

### ISSUE THREAD

**Issue by lop570** [AITYunivers/NebulaFD#3]
[PackFile\22:09:30.11] New packfile: mmfs2.dll
[PackFile\22:09:30.12] New packfile: mmf2d3d11.dll (Compressed)
[PackFile\22:09:30.13] New packfile: mmf2d3d9.dll (Compressed)
[PackFile\22:09:30.13] New packfile: mmf2d3d8.dll (Compressed)
[PackFile\22:09:30.13] New packfile: KcArray.mfx (Compressed)
[PackFile\22:09:30.13] New packfile: kcini.mfx (Compressed)
[PackFile\22:09:30.13] New packfile: parser.mfx (Compressed)
[PackFile\22:09:30.13] New packfile: txtblt.mfx (Compressed)
[PackFile\22:09:30.14] New packfile: ValueAdd.mfx (Compressed)
[PackFile\22:09:30.14] New packfile: kcfile.mfx (Compressed)
[PackFile\22:09:30.14] New packfile: Joystick2.mfx (Compressed)
[PackFile\22:09:30.14] New packfile: ctrlx.mfx (Compressed)
[PackFile\22:09:30.14] New packfile: kcwctrl.mfx (Compressed)
[PackFile\22:09:30.14] New packfile: joystick.mfx (Compressed)
[PackFile\22:09:30.14] New packfile: ZipObject.mfx (Compressed)
[PackFile\22:09:30.14] New packfile: fcMsgBox.mfx (Compressed)
[PackFile\22:09:30.14] New packfile: kccombo.mfx (Compressed)
[PackFile\22:09:30.14] New packfile: fcButton.mfx (Compressed)
[PackFile\22:09:30.14] New packfile: KcBoxB.mfx (Compressed)
[PackFile\22:09:30.14] New packfile: nvar.mfx (Compressed)
[PackFile\22:09:30.14] New packfile: fcMMF2params.mfx (Compressed)
[PackFile\22:09:30.14] New packfile: KcBoxA.mfx (Compressed)
[PackFile\22:09:30.14] New packfile: Perspective.mfx (Compressed)
[PackFile\22:09:30.14] New packfile: ForEach.mfx (Compressed)
[PackFile\22:09:30.14] New packfile: Parallaxer.mfx (Compressed)
[PackFile\22:09:30.14] New packfile: INI++15.mfx (Compressed)
[PackFile\22:09:30.15] New packfile: Easing.mfx (Compressed)
[PackFile\22:09:30.15] New packfile: XBOXGamepad.mfx (Compressed)
[PackFile\22:09:30.15] New packfile: adshow.mfx (Compressed)
[PackFile\22:09:30.15] New packfile: KcSyso.mfx (Compressed)
[PackFile\22:09:30.15] New packfile: gstorex.mfx (Compressed)
[PackFile\22:09:30.15] New packfile: AppPriority.mfx (Compressed)
[PackFile\22:09:30.15] New packfile: cctrans.dll (Compressed)
[PackFile\22:09:30.15] New packfile: waveflt.sft (Compressed)
[PackFile\22:09:30.15] New packfile: oggflt.sft (Compressed)
[PackFile\22:09:30.15] New packfile: aiffflt.sft (Compressed)
[PackFile\22:09:30.15] New packfile: mp3flt.sft (Compressed)
[PackFile\22:09:30.15] New packfile: modflt.sft (Compressed)
[CCNPackageData\22:09:30.16] Running 6/25/24 build.
[CCNPackageData\22:09:30.26] Game Header: PAMU
[CCNPackageData\22:09:30.26] Fusion Build: 292 (Fusion 2,5)
[CCNPackageData\22:09:30.26] Reading Chunk 0x2223 (AppHeader)
[CCNPackageData\22:09:30.26] Reading Chunk 0x2246 (AppCodePage)
[CCNPackageData\22:09:30.26] Reading Chunk 0x2251 (UnknownChunk)
[UnknownChunk\22:09:30.26] Unknown Chunk: 0x2251
[CCNPackageData\22:09:30.26] Reading Chunk 0x2224 (AppName)
[CCNPackageData\22:09:30.26] Reading Chunk 0x2225 (Author)
[CCNPackageData\22:09:30.26] Reading Chunk 0x223B (Copyright)
[CCNPackageData\22:09:30.26] Reading Chunk 0x222F (TargetFilename)
[CCNPackageData\22:09:30.26] Reading Chunk 0x222E (EditorFilename)
[CCNPackageData\22:09:30.26] Reading Chunk 0x223A (About)
[CCNPackageData\22:09:30.26] Reading Chunk 0x2235 (AppIcon)
[CCNPackageData\22:09:30.27] Reading Chunk 0x2245 (ExtendedHeader)
[CCNPackageData\22:09:30.27] Reading Chunk 0x224F (EngineVer)
[CCNPackageData\22:09:30.27] Reading Chunk 0x2232 (GlobalValues)
[CCNPackageData\22:09:30.27] Reading Chunk 0x2233 (GlobalStrings)
[CCNPackageData\22:09:30.27] Reading Chunk 0x2226 (MenuBar)
[CCNPackageData\22:09:30.27] Reading Chunk 0x222C (ExtensionData)
[CCNPackageData\22:09:30.27] Reading Chunk 0x2234 (Extensions)
[CCNPackageData\22:09:30.27] Reading Chunk 0x2231 (TransitionFile)
[CCNPackageData\22:09:30.27] Reading Chunk 0x2243 (ShaderBank)
[CCNPackageData\22:09:30.27] Reading Chunk 0x225A (DX9ShaderBank)
[CCNPackageData\22:09:30.28] Reading Chunk 0x2259 (TrueTypeFontBank)
[CCNPackageData\22:09:30.30] Reading Chunk 0x2258 (TrueTypeFontInfo)
[CCNPackageData\22:09:30.30] Reading Chunk 0x2253 (ObjectHeaders)
[CCNPackageData\22:09:30.31] Reading Chunk 0x2254 (ObjectNames)
[CCNPackageData\22:09:30.32] Reading Chunk 0x2255 (ObjectShaders)
[RuntimeType\22:09:30.32] The given key '5' was not present in the dictionary.

**Comment by AITYunivers** [comment]
And this mysterious game is?

**Comment by lop570** [comment]
uhh Sally.exe Whisper of Soul, weirdly enough both of it's demos work but the full game(the one I'm trying to dump) kinda breaks upon decompiling

**Comment by lop570** [comment]
Is the image bank like slightly broken or just theres too much content

**Comment by AITYunivers** [comment]
Should be fixed in 8b1cbe286c81dbce59c3474e885e331afcc3a65f, but the Image Bank on that game wont work due to the fix for it breaking other games.
