### ISSUE TITLE
Mapping.nmf empty or broken

### ISSUE THREAD

**Issue by Mathieu015** [AITYunivers/NebulaFD#6]
[Mapping - Before.txt](https://github.com/user-attachments/files/16326100/Mapping.-.Before.txt)
[Mapping.txt](https://github.com/user-attachments/files/16326101/Mapping.txt)
[Mapping five Nights at Candys.txt](https://github.com/user-attachments/files/16326105/Mapping.five.Nights.at.Candys.txt)

I don't know what the mapping file is used for.

**Comment by AITYunivers** [comment]
If you don't know how to use it, don't make a fucking issue. :)
