### ISSUE TITLE
Frame animation are scattered in images folder

### ISSUE THREAD

**Issue by Mathieu015** [AITYunivers/NebulaFD#7]
<img width="497" alt="2024-07-21 174856" src="https://github.com/user-attachments/assets/69f896ba-82f7-4adc-8c44-0b91a6e4102e">

**Comment by AITYunivers** [comment]
That's not an issue, please stop opening issues or I'll have to block your account.

**Comment by Mathieu015** [comment]
How is that not an issue?

**Comment by AITYunivers** [comment]
Because it's intended behaviour

**Comment by Mathieu015** [comment]
What am I supposed to do with that then?

**Comment by AITYunivers** [comment]
Open the mfa, extract it using Clickteam

**Comment by Mathieu015** [comment]
And what if I don't have Clickteam or don't want to extract hundreds of images manually?

**Comment by AITYunivers** [comment]
Well the first ones your problem, the second one, Clickteam lets you extract entire animations at once.

**Comment by Mathieu015** [comment]
And what if there's a lot of animations to export? Can I export them all at once?

**Comment by AITYunivers** [comment]
Nope, but it's either that, or coding your own decompiler

**Comment by Mathieu015** [comment]
Ok. Fine. Sorry to have bothered you.
