### ISSUE TITLE
Not being able to save file

### ISSUE THREAD

**Issue by 1JustJoey** [AITYunivers/NebulaFD#8]
So, it lets me decompile and everything, but it shows no file dialog or anywhere to save it.

**Comment by AITYunivers** [comment]
It decompiles to Nebula\Dumps\GameName

**Comment by 1JustJoey** [comment]
it didn't though. 
![image](https://github.com/user-attachments/assets/84994bdf-0a2d-45e8-b8bd-954c28b4bb1f)

**Comment by 1JustJoey** [comment]
> It decompiles to Nebula\Dumps\GameName

![image](https://github.com/user-attachments/assets/bf2d1e80-e2d6-4cd2-88f3-18ab268e3b0d)
no files are showing in uninstall tool, and i checked the directory and there were none there.
